cadastroDeTrancao/config/routes.rb
Rails.application.routes.draw do
  resources :funcao_transacionals

end

cadastroDeTrancao/app/models/funcao_transacional.rb
class FuncaoTransacional < ActiveRecord::Base
end

cadastroDeTrancao/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

cadastroDeTrancao/app/controllers/funcao_transacionals_controller.rb
class FuncaoTransacionalsController < ApplicationController
  before_action :set_funcao_transacional, only: [:show, :edit, :update, :destroy]

  # GET /funcao_transacionals
  # GET /funcao_transacionals.json
  def index
    @funcao_transacionals = FuncaoTransacional.all
  end

  # GET /funcao_transacionals/1
  # GET /funcao_transacionals/1.json
  def show
  end

  # GET /funcao_transacionals/new
  def new
    @funcao_transacional = FuncaoTransacional.new
  end

  # GET /funcao_transacionals/1/edit
  def edit
  end

  # POST /funcao_transacionals
  # POST /funcao_transacionals.json
  def create
    @funcao_transacional = FuncaoTransacional.new(funcao_transacional_params)

    respond_to do |format|
      if @funcao_transacional.save
        format.html { redirect_to @funcao_transacional, notice: 'Funcao transacional was successfully created.' }
        format.json { render :show, status: :created, location: @funcao_transacional }
      else
        format.html { render :new }
        format.json { render json: @funcao_transacional.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcao_transacionals/1
  # PATCH/PUT /funcao_transacionals/1.json
  def update
    respond_to do |format|
      if @funcao_transacional.update(funcao_transacional_params)
        format.html { redirect_to @funcao_transacional, notice: 'Funcao transacional was successfully updated.' }
        format.json { render :show, status: :ok, location: @funcao_transacional }
      else
        format.html { render :edit }
        format.json { render json: @funcao_transacional.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcao_transacionals/1
  # DELETE /funcao_transacionals/1.json
  def destroy
    @funcao_transacional.destroy
    respond_to do |format|
      format.html { redirect_to funcao_transacionals_url, notice: 'Funcao transacional was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcao_transacional
      @funcao_transacional = FuncaoTransacional.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcao_transacional_params
      params.require(:funcao_transacional).permit(:nameFunc, :typeFunc, :param1, :param2, :complexity, :qntdPF, :nameCounter, :registry)
    end
end

cadastroDeTrancao/app/helpers/application_helper.rb
module ApplicationHelper
end

cadastroDeTrancao/app/helpers/funcao_transacionals_helper.rb
module FuncaoTransacionalsHelper
end

cadastroDeTrancao/app/views/funcao_transacionals/_form.html.erb
<%= form_for(@funcao_transacional) do |f| %>
  <% if @funcao_transacional.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@funcao_transacional.errors.count, "error") %> prohibited this funcao_transacional from being saved:</h2>

      <ul>
      <% @funcao_transacional.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <form data-toggle="validator">
    <div class="field">
      <div class="form-group">
        <label for="nameFunc">Nome</label>
        <input class="form-control" type="text" id="funcao_transacional.nameFunc" 
          placeholder="Insira o nome da função" required>
      </div>  
    </div>

    <div class="field">
      <div class="form-group">
        <label for="typeFunc">Tipo da Função</label>
        <select class="form-control" id="funcao_transacional.typeFunc">
        <option>--selecione uma opção</option>
          <option value=1>EE</option>
          <option value=2>CE</option>
          <option value=3>SE</option>
        </select>
      </div>
    </div>

    <div class="field">
      <div class="form-group">
        <label for="param1">Quantidade de ALRs</label>
        <input class="form-control" type="text" id="funcao_transacional.param1" 
          placeholder="Insira quantidade de ALRs" required>
      </div> 
    </div>
    
    <div class="field">
      <div class="form-group">
        <label for="param2">Quantidade de DERs</label>
      <input class="form-control" type="text" id="funcao_transacional.param2" 
        placeholder="Insira quantidade de DERs" required>
      </div>
    </div>
    
    <div class="field">
      <div class="form-group">
        <label for="complexity">Complexidade da Função</label>
      <input class="form-control" type="text" id="funcao_transacional.complexity" 
        placeholder="">
      </div>
    </div>
    
    <div class="field">
    <div class="form-group">
      <label for="qntdPF">Quantidade de PF - Pontos de Função</label>
    <input class="form-control" type="text" id="funcao_transacional.qntdPF" 
      placeholder="">
    </div>
  </div>

    <div class="field">
      <div class="form-group">
        <label for="nameCounter">Informe Seu Nome</label>
        <input class="form-control" type="text" id="funcao_transacional.nameCounter" 
          placeholder="Insira seu nome" required>
      </div>
    </div>

    <div class="field">
      <%= f.label :registry %><br>
      <%= f.datetime_select :registry %>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
  <script src="js/validator.min.js"></script>
<% end %>

cadastroDeTrancao/app/views/funcao_transacionals/edit.html.erb
<h1>Editing Funcao Transacional</h1>

<%= render 'form' %>

<%= link_to 'Show', @funcao_transacional %> |
<%= link_to 'Back', funcao_transacionals_path %>

cadastroDeTrancao/app/views/funcao_transacionals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Funções Transacionais</h1>

<table>
  <tbody>
    <% @funcao_transacionals.each do |funcao_transacional| %>
      <tr>
        <td><%= funcao_transacional.nameFunc %></td>
        <td><%= funcao_transacional.typeFunc %></td>
        <td><%= funcao_transacional.param1 %></td>
        <td><%= funcao_transacional.param2 %></td>
        <td><%= funcao_transacional.complexity %></td>
        <td><%= funcao_transacional.qntdPF %></td>
        <td><%= funcao_transacional.nameCounter %></td>
        <td><%= funcao_transacional.registry %></td>
        <td><%= link_to 'Show', funcao_transacional %></td>
        <td><%= link_to 'Edit', edit_funcao_transacional_path(funcao_transacional) %></td>
        <td><%= link_to 'Destroy', funcao_transacional, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<a class="btn btn-primary" href="/funcao_transacionals/new" role="button">Incluir Nova Função</a>

cadastroDeTrancao/app/views/funcao_transacionals/new.html.erb
<h1>New Funcao Transacional</h1>

<%= render 'form' %>

<%= link_to 'Back', funcao_transacionals_path %>

cadastroDeTrancao/app/views/funcao_transacionals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Namefunc:</strong>
  <%= @funcao_transacional.nameFunc %>
</p>

<p>
  <strong>Typefunc:</strong>
  <%= @funcao_transacional.typeFunc %>
</p>

<p>
  <strong>Param1:</strong>
  <%= @funcao_transacional.param1 %>
</p>

<p>
  <strong>Param2:</strong>
  <%= @funcao_transacional.param2 %>
</p>

<p>
  <strong>Complexity:</strong>
  <%= @funcao_transacional.complexity %>
</p>

<p>
  <strong>Qntdpf:</strong>
  <%= @funcao_transacional.qntdPF %>
</p>

<p>
  <strong>Namecounter:</strong>
  <%= @funcao_transacional.nameCounter %>
</p>

<p>
  <strong>Registry:</strong>
  <%= @funcao_transacional.registry %>
</p>

<%= link_to 'Edit', edit_funcao_transacional_path(@funcao_transacional) %> |
<%= link_to 'Back', funcao_transacionals_path %>

cadastroDeTrancao/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CadastroDeTrancao</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>